-- Widgets table seeds here (Example)

INSERT INTO menus (restaurant_id, name, imgURL, description, category, price)
VALUES (1,
  'Meal Deal For One',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/cedc03da-7427-4c31-ad48-25a7687a2e75.png',
  'Need to satisfy your pizza craving? Choose your favourite small pizza, and enjoy it with a starter Caesar or Garden salad. *Serves 1-2* Cannot be combined with any other offers.',
  'meal-deals', 19.99),
 (1,
  'Pizza, Pasta & Salad Meal Deal',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/0ee03866-9f12-43a3-8303-ade96fbc5ba8.png',
  'Craving pizza and pasta, BP has you covered! Choose your favourite medium pizza, one of our gourmet pastas, and top it all off with an entree Caesar or Garden salad! *Serves 2-3* Cannot be combined with any other offers.',
  'meal-deals', 40.49),
 (1,
  'Pizza & Wings Meal Deal',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f2e3be36-5d42-4b34-8bae-dfc67123d695.png',
  'Feed the entire crew! Choose your favourite large pizza, a single order of wings, an entrée Caesar or Garden salad and an 8" Bandera Bread. *Serves 3-4 - Great for families* Cannot be combined with any other offers.',
  'meal-deals', 51.99),
 (1,
  'Game Day Meal Deal',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/5f8a80c7-f60d-4fed-b4f8-34604b3d7aa5.png',
  'BP has your game day meal ready with the perfect pair. Choose two of your favourite medium pizzas and one triple order of wings with 2 dips of your choice. *Serves 5-6* Cannot be combined with any other offers.',
  'meal-deals', 63.99),
  (1,
  'All Meat Bites®',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/d4a95aa1-256a-40fe-8d61-5cdfc3d89a75.png',
  'Seasoned chicken breast pieces, lightly breaded and fried. Tossed in your choice of sauce and served with a dip.',
  'apps-and-shareables', 17.29),
 (1,
  'Fried Wings',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/29f2f9d8-e785-4df3-a51e-267ef105c721.png',
  'Our famous wings, fried until golden and crispy. Tossed in your choice of sauce and served with a dip.',
  'apps-and-shareables', 16.29),
 (1,
  'Oven-Roasted Wings',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/29f2f9d8-e785-4df3-a51e-267ef105c721.png',
  'Our famous wings, baked twice to perfection. Tossed in your choice of sauce and served with a dip.',
  'apps-and-shareables', 16.29),
 (1,
  'Wings Combo',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/28c7ab9d-8401-4ed9-8cfa-61b9559e4df0.png',
  'A starter size of your favourite wings and a side of your choice.',
  'apps-and-shareables', 18.79),
 (1,
  'Bandera Pizza Bread',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/0d759fe9-188b-436a-a818-b65d571ec7e3.png',
  'Pizza bread, Italian spices, pizza mozzarella and freshly grated Parmesan. Served with Santa Fe ranch dip.',
  'apps-and-shareables', 13.29),
 (1,
  'Bostons Pizza Bread',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/42b17210-57bd-4c5f-b4f1-56647b13e602.png',
  'Pizza dough baked and seasoned with garlic, herbs and Parmesan.',
  'apps-and-shareables', 9.79),
 (1,
  'Garlic Pizza Fingers',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/b03d8dcc-b5c8-4d9c-8189-ddd3608c2bc9.png',
  'Pizza dough brushed with garlic and baked with melted pizza mozzarella. Served with donair sauce.',
  'apps-and-shareables', 15.49),
 (1,
  'Garden Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/65275430-7bee-46ef-9e9b-e6152078bb6e.png',
  'Garden greens, red peppers, red onions, cucumbers, carrots, beets and citrus vinaigrette.',
  'apps-and-shareables', 10.99),
 (1,
  'Caesar Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/6e7f5474-e08d-4650-bb67-9f1c106b45f3.png',
  'Romaine, croutons, bacon and freshly grated Parmesan.',
  'apps-and-shareables', 10.99),
 (1,
  'Cactus Cut Potatoes',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3a9261f8-d4d0-4535-8224-b527a128892b.png',
  'Spicy and thinly sliced fried potatoes served with our signature cactus dip.',
  'apps-and-shareables', 11.79),
 (1,
  'Hearty Jalapeño Popper Dip',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/5ee214ef-6d1a-4670-b709-68044ae8fe99.png',
  'Made with a blend of rich Canadian cheeses, jalapeño peppers, smoked bacon, and garlic. Served piping hot with our signature Cactus Cut Potatoes.',
  'apps-and-shareables', 15.79),
 (1,
  'Deep Fried Pickle Wedges',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/2a6ad86f-8fcc-4571-9664-af3584ebf431.png',
  'Dill pickle spears lightly fried and served with buttermilk ranch dip.',
  'apps-and-shareables', 10.49),
 (1,
  'The Triple Play',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/5d9350b2-d16e-4c8e-9566-7cbfc14f37b2.png',
  'A shareable portion of three guest favourites: Bandera Bread with Santa Fe Ranch dip, our Signature Chicken Thai Bites, and Cactus Cut Potatoes served with cactus dip.',
  'apps-and-shareables', 21.99),
 (1,
  'Crispy Cajun Shrimp',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/6fbf6736-386a-4964-b36f-258976087357.png',
  'Breaded jalapeño shrimp, fried and then tossed in our Cajun dry rub. Served with a sweet and spicy mango dip.',
  'apps-and-shareables', 14.29),
 (1,
  'Garlic Parmesan Fries',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e0595d6b-146c-4a69-87bb-4a07eca7f62f.png',
  'Take your fries to the next level. Golden fries tossed with garlic and Parmesan cheese. Served with our signature cactus dip.',
  'apps-and-shareables', 9.49),
 (1,
  'Kick''N Onion Rings',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/60bef312-650b-4601-82fc-03166304d4fe.png',
  'Drizzled with TABASCO® barrel-aged Sriracha. Served with house-made honey dill dip.',
  'apps-and-shareables', 10.79),
 (1,
  'Thai Bites',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/cdcfbfd2-a185-4d3d-9a3f-78b5f291458b.png',
  'Breaded chicken breast tossed in sweet Thai chili sauce and served with crunchy Asian noodles, carrots, green onions, and sesame seeds.',
  'apps-and-shareables', 15.29),
 (1,
  'Spinach And Artichoke Dip',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/8af503ea-98ef-4394-9301-dd6665bb9dc7.png',
  'Spinach, artichokes, roasted garlic, pizza mozzarella, Cajun seasoning, tomatoes, feta, and Parmesan. Served with pizza bread.',
  'apps-and-shareables', 15.29),
 (1,
  'Chicken Fingers',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ac42c7c7-7533-41e2-8180-5a0b74ce73f2.png',
  'Lightly breaded chicken breast filet served with your choice of dipping sauce.',
  'apps-and-shareables', 14.79),
 (1,
  'Classic Nachos - Starter Size',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e5643510-8525-4ff4-8392-f69f83852d67.png',
  'Starter size of hand-cut tortilla chips topped with cheddar, pizza mozzarella, green peppers, olives, jalapeño peppers, tomatoes, and green onions. Served with salsa, sour cream, and your choice of protein. Choose from: Seasoned Ground Beef, BBQ Chicken, Spicy Chicken',
  'apps-and-shareables', 16.99),
 (1,
  'Smoked Meat Poutine',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f3ba238b-7223-4b07-a71c-1c72c001a9d9.png',
  'Fries, cheese curds, Montréal Dunn’s smoked meat covered with poutine sauce and finished with julienne pickles and a drizzle of mustard.',
  'apps-and-shareables', 9.99),
 (1,
  'Poutine',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/c4c0b7b7-3fae-43ad-8655-dd99870ec42c.png',
  'Fries smothered in gravy and cheese curds.',
  'apps-and-shareables', 7.99),
 (1,
  'Bp''S French Onion Soup',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/9d6fc1a7-5817-4226-8783-c9309c4c9152.png',
  'A rich beef broth made with sherry and sweet onions. Topped with house-made crostini, Gouda, provolone, pizza mozzarella, and Parmesan, then baked until the cheese is a bubbly golden brown.',
  'apps-and-shareables', 10.39),
  (1,
  'Mac & Cheese⁵',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/573572ca-6af9-4ddf-b4f6-ac416507d267.png',
  'Macaroni noodles tossed in a super cheesy cream sauce made with cheddar, provolone, Gouda, mozzarella, and Parmesan cheese. We then top it with more cheese, and panko breadcrumbs, and bake it until golden brown. Served with garlic toast.',
  'pasta-tuesday',
  11.5),
 (1,
  'Spicy Buffalo Chicken Mac & Cheese',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e4570580-2785-4acd-beb5-6c1eb34b2143.png',
  'Cheesy Buffalo Alfredo sauce tossed with red peppers and macaroni noodles, topped with cheese and panko breadcrumbs. Then baked until golden brown, and finished with crispy Buffalo chicken bites, green onions, and Parmesan cheese.',
  'pasta-tuesday',
  14.95),
 (1,
  'Jambalaya Fettuccini',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/74ed9fd6-ceb2-4a08-b52d-cd0ed63cab63.png',
  'Chicken breast, shrimp, spicy Italian sausage, tomatoes, green peppers, green onions, Cajun seasoning, and marinara sauce.',
  'pasta-tuesday',
  13.24),
 (1,
  'Baked Seven Cheese Ravioli',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ad182745-b0e4-4a1b-8108-2b7cba9cc5d5.png',
  'Ravioli stuffed with Parmesan, Emmental, ricotta, fontina, and Romano, baked with pizza mozzarella and cheddar, and your choice of sauce.',
  'pasta-tuesday',
  12.58),
 (1,
  'Hungry Carnivore',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/60a7238d-25cb-4ee0-8cbb-5f1a844c9c65.png',
  'Penne Bolognese loaded with Spicy Italian sausage, meatballs, pepperoni, and some vegetables for good measure. Served with bacon-crusted garlic cheese bread.',
  'pasta-tuesday',
  11.7),
 (1,
  'Creamy Mushroom & Spinach Bake',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/b133c8bb-c3a7-43bf-8fab-e5c83c0e9399.png',
  'Baby spinach, mushrooms, and penne tossed in a garlic pesto cream sauce. Baked with Gouda, provolone, pizza mozzarella and Parmesan cheese.',
  'pasta-tuesday',
  11.0),
 (1,
  'Chicken And Mushroom Fettuccini',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/37b1591f-677e-4c20-b939-22463b711e36.png',
  'Chicken breast, mushrooms, tomatoes, and green onions, with Alfredo sauce.',
  'pasta-tuesday',
  11.67),
 (1,
  'Smoky Mountain Spaghetti & Meatballs',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e6b5bba1-a752-494e-9583-b168f1b3642a.png',
  'A mountainous serving of spaghetti smothered in Bolognese sauce, then topped with three meatballs and cheddar cheese.',
  'pasta-tuesday',
  11.59),
 (1,
  'Parmesan Shrimp Alfredo',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/4d8b1f35-b4d1-4fd5-a517-2c68a8327ee1.png',
  'Garlic sautéed shrimp tossed with spaghetti in a parmesan white wine Alfredo sauce with seasoned spinach and cherry tomatoes. Finished with freshly grated Parmesan and a zest of lime.',
  'pasta-tuesday',
  12.92),
 (1,
  'Boston''S Lasagna',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3f1f24e7-06e2-474b-b9e8-1c17655b7b54.png',
  'A baked combination of beefy Bolognese sauce, lasagna noodles, and pizza mozzarella, with freshly grated Parmesan.',
  'pasta-tuesday',
  11.78),
 (1,
  'Fettuccini',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/b1c29d4f-df64-4492-9dd0-99e239bc57a8.png',
  'These ''little ribbons'' are the perfect partner to our alfredo sauce.',
  'pasta-tuesday',
  14.67),
 (1,
  'Penne',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/a51bc0c6-cd3d-4862-974c-66bd36d6907a.png',
  'Tube-shaped pasta to hold your favourite sauce.',
  'pasta-tuesday',
  12.0),
 (1,
  'Spaghetti',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/b91de4e1-1a5c-4ed3-bacc-1fa612d174a5.png',
  'Pairs beautifully with meatballs and meat sauce!',
  'pasta-tuesday',
  12.54),
 (1,
  'Macaroni',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/573572ca-6af9-4ddf-b4f6-ac416507d267.png',
  'The classic noodle that pairs wonderfully with your favourite cheese.',
  'pasta-tuesday',
  11.35),
 (1,
  'Glutenwise® Pasta',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/662be59a-6d61-47fe-a89e-75f64539eede.png',
  'Our GlutenWise® pasta with your choice of sauce and toppings.',
  'pasta-tuesday',
  13.21),
  (1,
  'Honey Dill Chicken Bowl',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/937ee059-d5b9-4def-b9a1-3819e33120f9.png',
  'Your choice of breaded or grilled chicken breast drizzled with honey dill served over a warm blend of quinoa and rice with spinach, cherry tomatoes, guacamole, beets, carrots, roasted red peppers, and cucumbers.',
  'bowls-and-salads',
  19.74),
 (1,
  'Salmon Power Bowl',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/c20bdbf4-bbe0-4671-bd81-5a8fb45cf646.png',
  'Oven‑roasted citrus and cumin glazed salmon, served over a warm blend of quinoa and rice with spinach, cherry tomatoes, guacamole, beets, carrots, roasted red peppers, cucumbers, and sesame seeds.',
  'bowls-and-salads',
  23.43),
 (1,
  'Fiesta Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/0fb0622d-02ac-4ee5-829b-d943151239e3.png',
  'Romaine tossed in avocado lime dressing, and topped with diced ancho chipotle chicken, fire roasted corn, onions and peppers, green onions, cheddar cheese, tomatoes, guacamole, and cilantro.',
  'bowls-and-salads',
  17.74),
 (1,
  'Chicken Pecan Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ca9fe097-52a9-47fc-b407-42c702b9d864.png',
  'Garden greens, candied pecans, pizza mozzarella, cheddar, bacon, cucumbers, carrots, tomatoes, and ranch dressing. Choose from grilled chicken breast or breaded chicken breast.',
  'bowls-and-salads',
  18.53),
 (1,
  'Pineapple, Beet & Goat Cheese Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/db55acad-7d46-4990-ac42-8fc3a7ce28d2.png',
  'Garden greens, pineapple, beets, red onions, roasted red peppers, goat cheese, slivered almonds, and balsamic dressing.',
  'bowls-and-salads',
  18.88),
 (1,
  'Chicken Caesar Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/b7576a84-adb6-4f2f-98ca-a3ab8e7d4084.png',
  'Grilled chicken breast, romaine, croutons, bacon, and freshly grated Parmesan.',
  'bowls-and-salads',
  23.24),
 (1,
  'Caesar Salad',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/6e7f5474-e08d-4650-bb67-9f1c106b45f3.png',
  'Romaine, croutons, bacon and freshly grated Parmesan.',
  'bowls-and-salads',
  19.63),
  (1,
  'Kick''N Memphis Chicken Sandwich',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f02ef365-bfad-4496-a594-eb4c50951a63.png',
  'Buttermilk-breaded fried chicken tossed in Memphis hot sauce, cheddar, bacon, ranch dressing, lettuce, tomatoes and a pickle on a brioche bun.',
  'sandwiches',
  16.22),
 (1,
  'Honey Dill Fried Chicken Sandwich',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/99399141-f8b0-4e0b-9bf1-dcce0c58c574.png',
  'A buttermilk-fried chicken breast, topped with house-made honey-dill sauce, bacon, lettuce, tomato, and pickles, on a toasted brioche bun.',
  'sandwiches',
  18.09),
 (1,
  'The Big Dipper',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3abab0f5-e538-4938-8d8b-445949a91690.png',
  'Sliced steak, roasted red peppers, pizza mozzarella, and panko-crusted onion rings. Served with horseradish mayo and sweet onion au jus.',
  'sandwiches',
  19.24),
 (1,
  'Grilled Chicken Clubhouse',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e427f3b7-f89f-4db0-bc6e-24039011d043.png',
  'Garlic cheese baked baguette layered with chicken breast, bacon, lettuce and fresh tomato, drizzled with our secret sauce.',
  'sandwiches',
  15.91),
 (1,
  'Boston Brute',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/86bfe4c8-eb5c-4bb2-8944-99f8912bac16.png',
  'Genoa salami, pepperoni, smoked ham, pizza mozzarella, onions, and our signature pizza sauce. Served with beefy Bolognese sauce.',
  'sandwiches',
  17.95),
 (1,
  'Thai Chicken Wrap',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3b2b063e-122e-4302-8492-537dd43b442c.png',
  'Chicken breast, lettuce, red onions, carrots, cilantro, mayo, and crunchy Asian noodles, tossed in our Thai chili sauce and wrapped in a grilled flour tortilla. Choose from grilled chicken breast or breaded chicken breast.',
  'sandwiches',
  17.43),
 (1,
  'Montreal Smoked Meat Sandwich',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/d3f14cd7-e304-416c-bb8d-19c818e77935.png',
  'Montréal Dunn’s smoked meat, pizza mozzarella, mustard, and a pickle, served on toasted marble rye bread.',
  'sandwiches',
  16.08),
 (1,
  'Tacos',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/6f5a63e0-3c96-4887-92e5-e3e316dbe6e2.png',
  'Three soft tacos with your choice of protein, creamy lime coleslaw, pizza mozzarella, tomatoes, ancho chipotle sauce, and cilantro.',
  'sandwiches',
  19.0),
 (1,
  'Boston-Sized Burger',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/9eaf40d8-628a-4101-b5de-a8e2bacc488d.png',
  'Two-grilled quarter-pound patties, topped with cheddar, lettuce, tomatoes, red onions, pickles, and our signature cactus dip, on a brioche bun.',
  'sandwiches',
  16.97),
 (1,
  'Whiskey Burger',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/a0977e50-97f6-4939-8341-cf8392a6ccc1.png',
  'Loaded with bacon, Bourbon BBQ sauce, lettuce, tomatoes, red onions, and pickles, on a toasted brioche bun.',
  'sandwiches',
  16.88),
 (1,
  'Bp’S Perfectly Plant-Based Burger',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/2e887a59-68de-43c1-bcf0-23609f14232c.png',
  'Our plant-based burger topped with lettuce, tomatoes, red onions, pickles & mayonnaise, on a toasted brioche bun.',
  'sandwiches',
  17.72),
  (1,
  'Slow-Roasted Pork Back Ribs',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/4e3a220b-6c4f-410a-88ce-d7833f939bed.png',
  'Our tender ribs are slow-cooked with our own blend of spices, and finished with your choice of sauce. Served with garlic toast, coleslaw, and your choice of one side.',
  'mains',
  22.89),
 (1,
  'Chicken Parmesan',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/1d596dfd-b07f-4fb4-868e-11f32fcb4465.png',
  'Buttermilk-breaded fried chicken breast, topped with our marinara sauce and pizza mozzarella. Served with garlic toast, spaghetti marinara, and your choice of one side.',
  'mains',
  23.36),
 (1,
  'Pizzaghetti',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f5546f6f-04ed-412e-bdce-ca9645fe3631.png',
  'Choice of La Québécoise® Boston or pepperoni pizza served with spaghetti and your choice of our beefy Bolognese or signature marinara sauce.',
  'mains',
  22.78),
  (1,
  'Bugs ''N'' Cheese',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/fe9e3e63-fa9d-4964-b7b2-e0a027df39a7.png',
  'Colourful bug-shaped pasta, pizza mozzarella, and Alfredo sauce.',
  'kids-menu',
  10.36),
 (1,
  'Chicken Fingers',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/32679134-5b68-4a99-8524-00f330167409.png',
  'Served with plum sauce for dipping.',
  'kids-menu',
  8.62),
 (1,
  'Sauced-Up Crispy Chicken Fingers',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/7bc2cae1-d958-4582-834f-1687593f6e46.png',
  'Crispy Chicken Fingers tossed in your choice of Mild, BBQ, or Honey Garlic sauce. Served with ranch for dipping.',
  'kids-menu',
  9.75),
 (1,
  'Super Spaghetti',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/71f1ccfd-ba14-4b9f-893d-223614d58dce.png',
  'Choose your sauce, served on the side: Tomato Sauce (Marinara), Meat Sauce.',
  'kids-menu',
  8.63),
 (1,
  'Pint-Sized Pizza',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/59402816-64bb-4752-b729-b74208f9aed4.png',
  'Pizza sauce, pizza mozzarella, and any topping you want – just pick one!',
  'kids-menu',
  10.25),
 (1,
  'Kids Cheese Burger',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/28f20334-3210-4c88-9e56-dc2e3b78e2ef.png',
  '100% Canadian beef burger, flame grilled, and topped with Canadian cheddar.',
  'kids-menu',
  8.96),
 (1,
  'Big Kids'' Bugs ''N'' Cheese',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/175e8fc5-2a9d-4301-ba3a-04d5fa7e0f89.png',
  'A ''big kids'' portion of our colourful bug shaped pasta, pizza mozzarella and Alfredo sauce.',
  'kids-menu',
  10.3),
 (1,
  'Spaghetti & Meatballs',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/a564bc21-8b76-48fd-87e1-b3dce400ece2.png',
  'Noodles tossed in your choice of: Tomato Sauce, Meat Sauce.',
  'kids-menu',
  10.53),
 (1,
  'Hungry Kids Pizza (8")',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/24ba9ac4-ec53-492a-a2b1-84aba2b36b65.png',
  'The perfect size for a hungry kid. Pizza sauce, pizza mozzarella and any two toppings you want.',
  'kids-menu',
  8.83),
 (1,
  'Kids Wings',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/8da201a1-90a0-40a1-a554-eb167ebc0d51.png',
  'Your choice of 5 Fried Wings or Oven-Roasted Wings tossed in your choice of sauce: Mild, BBQ or Honey Garlic',
  'kids-menu',
  10.03),
  (1,
  'Quinoa & Rice Blend',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/966e0dc7-fb44-4aed-99a2-a204665d1def.png',
  '*We are experiencing a shortage of quinoa rice blend, and as a result, it may be substituted with a whole grain brown rice blend instead.',
  'sides',
  2.94),
 (1,
  'Sweet Potato Fries',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/52ed8590-8442-4a82-8c11-4fff59824c5b.png',
  'Slices of sweet yams, fried until golden and crispy and served with a side of our Sriracha Ranch dip.',
  'sides',
  4.46),
 (1,
  'Fries',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/87fa2348-c076-40e9-85d5-cec5a64330e0.png',
  'No one''s going to be mad at you because you ordered too many fries.',
  'sides',
  4.57),
 (1,
  'Garlic Mashed Potatoes',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f1b3235b-a538-4327-9243-dd5466610237.png',
  'A heaping helping of garlicky, fluffy carb-a-licious goodness.',
  'sides',
  4.96),
 (1,
  'Chicken Breast',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/37452f20-e6e4-4635-bad5-6d15719e16da.png',
  '',
  'sides',
  2.64),
 (1,
  'Cajun Chicken Breast',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/9c6be1ca-2751-4930-9cb2-bf4a66638259.png',
  '',
  'sides',
  3.36),
 (1,
  'Garlic Toast',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/aea7623e-7f95-42d6-9aef-4bc9c2b4c6a6.png',
  'Fresh from the oven, brushed with butter and garlic.',
  'sides',
  2.55),
 (1,
  'Coleslaw',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3f04576a-c0c8-4fa8-ae29-ebb42dbf516c.png',
  '',
  'sides',
  4.31),
 (1,
  'Honey Dill Dip',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3e3e3063-ae86-454b-8ccc-3c995c18df2f.png',
  '',
  'sides',
  4.84),
 (1,
  'Alfredo Sauce',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/526fda31-eaae-459c-8be6-7408293319e6.png',
  'Creamy, white-winey, parmesany heaven. Not just for fettuccini anymore.',
  'sides',
  2.15),
 (1,
  'Bolognese Sauce',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e173e489-0150-46b0-8d05-35b5682d0370.png',
  'Let''s face it: pasta is just a holder anyway for this meat & tomato classic.',
  'sides',
  6.38),
 (1,
  'Cactus Dip',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/2bc33992-d8a6-4a41-a2d3-8f524e16fb07.png',
  'A rich blend of crushed chilies, green onion, sour cream and parmesan: a BP original & a crowd favourite.',
  'sides',
  3.03),
 (1,
  'Rosé Sauce',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/623d4ed1-ded5-4b9f-9e32-35d76199a2eb.png',
  'A mix of our Alfredo and Pomodoro tomato sauces. Very side-order friendly.',
  'sides',
  5.52),
 (1,
  'Gravy',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/34730fce-edd3-4c40-8fb5-844e0fec8d79.png',
  '',
  'sides',
  4.6),
 (1,
  'Pizza Sauce',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/28cecac1-3f73-4521-80c1-c63103a1b7f5.png',
  'Also known as our Awesome-On-Everything Sauce.',
  'sides',
  2.0),
 (1,
  'Tomato Marinara',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/fd1add68-3fda-44ee-909b-8de042f5a98a.png',
  'Delicious, and counts as a serving of vegetables, believe it or not.',
  'sides',
  2.59),
 (1,
  'Salsa',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/55d3a7b9-7629-4c12-8e77-d92809b86d7e.png',
  'Take a hike ketchup packets: it''s all about extra salsa on the side.',
  'sides',
  5.37),
 (1,
  'Sour Cream',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/54b6bf25-cd67-4f95-a606-312e18dedbf1.png',
  'Extra sour cream always cools everything down.',
  'sides',
  4.66),
 (1,
  'Guacamole',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/d2e5b838-2a6b-4208-931b-d207d01d49b1.png',
  '',
  'sides',
  5.72),
 (1,
  'Blue Cheese Dressing',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f86f4d30-6fdc-4b0f-afb8-de22ac4f8705.png',
  'Why not acquire an extra helping of this acquired taste?',
  'sides',
  2.14),
 (1,
  'Caesar Dressing',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/0648796f-8cba-4c41-921b-e225a82a86f6.png',
  'Order extra. So no one has to stab anyone in the back.',
  'sides',
  4.69),
 (1,
  'Ranch Dressing',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ddb003be-16e0-4e03-a7d2-0d38f3848111.png',
  'Fries. Veggies. Fingers. An extra tub of ranch is always perfect for dipping.',
  'sides',
  6.45),
 (1,
  'Chipotle',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/fc93ea32-306c-428a-94a5-89428e108f4a.png',
  '',
  'sides',
  4.5),
 (1,
  'Honey Mustard',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/d25476a6-6337-4d50-baea-ddb386c9b89b.png',
  '',
  'sides',
  5.19),
 (1,
  'Mayo',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/6cbf0251-9bf3-45d3-9804-3f77371c3220.png',
  '',
  'sides',
  6.35),
 (1,
  'Santa Fe',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/1c43a78b-fac1-490b-a27d-15e2289f1e3e.png',
  '',
  'sides',
  5.83),
 (1,
  'Sriracha Ranch',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/b7f1e74a-3fd0-4e11-8afe-554fe963defe.png',
  '',
  'sides',
  4.94),
  (1,
  'Salted Caramel Panookie',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/097b0711-8753-4ef0-b181-aa8dc45fa4e2.png',
  'The panookie is back! A giant, freshly baked, salted caramel chocolate chunk pizza pan cookie and drizzled with caramel sauce.',
  'desserts',
  7.36),
 (1,
  'Chocolate Explosion',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/417263dc-40ca-4c62-b5c0-32d5f9aa7a10.png',
  'Creamy chocolate mousse with chunks of cheesecake, caramel, toffee, pecans, and almonds on a chocolate crust.',
  'desserts',
  8.05),
 (1,
  'New York Cheesecake',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/0c6216b8-0c36-48c0-99cd-5f59f874b49c.png',
  'Traditional New York-style cheesecake with a graham cracker crust. Choose your sauce: Chocolate, Caramel, Berry',
  'desserts',
  5.19),
 (1,
  'Chocolate Brownie Addiction',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/722f2ec6-a58b-41d2-b9b3-974af5bc2fb4.png',
  'Two warm chocolate brownies topped with two scoops of vanilla ice cream and drizzled with our caramel and chocolate sauces. *Not served with ice cream for takeout and delivery.',
  'desserts',
  3.59),
 (1,
  'Bite-Sized Chocolate Brownie Addiction',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ff087938-098e-4175-978f-13bcecea9944.png',
  'One warm chocolate brownie topped with a scoop of vanilla ice cream and drizzled with our caramel and chocolate sauces. *Not served with ice cream for takeout and delivery.',
  'desserts',
  8.14),
  (1,
  'Alexander Keith''S',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/cf61d5a3-f59b-4ae2-bd37-10a4c9be4e5f.png',
  'Alexander Keith''s, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  20.62),
 (1,
  'Kokanee',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3bb9f73a-22e7-43ea-959f-93c8f153b215.png',
  'Kokanee, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  17.06),
 (1,
  'Molson Export',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/046eaa35-c38b-49da-99d5-b0106e7ca30b.png',
  'Molson Export, 341 mL Bottle. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  9.31),
 (1,
  'Budweiser',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ffc03371-b46c-4a9e-a54f-68f868743b92.png',
  'Budweiser, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  21.63),
 (1,
  'Coors Light',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/9e67c7c0-28b8-45c7-bbb0-544336118c28.png',
  'Coors Light, 355 mL Can (341 mL bottle in Quebec). Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  15.24),
 (1,
  'Heineken',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/a36e7fbf-a4d0-470c-a7cd-a5faa5f8d3da.png',
  'Heineken, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  17.79),
 (1,
  'Bud Light',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/5471c1ff-dd8c-4f18-9967-d036d0c8fb17.png',
  'Bud Light, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  7.92),
 (1,
  'Molson Canadian',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/f273156c-2b86-4d08-b484-6169299f2ee0.png',
  'Molson Canadian, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  10.46),
 (1,
  '4-Pack Mix And Match Beer',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/4712fcb3-c4fc-4fa2-a2d0-de36c7f9a729.png',
  '4-pack domestic beer - mix and match 4x355ml Cans. Choose from Coors Light, Molson Canadian, Budweiser and Bud Light. Take-out and delivery only.',
  'alcoholic-beverages',
  11.9),
 (1,
  '4-Pack Mix And Match Beer',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/105df96e-2768-41b9-bea9-fa8222d83a41.png',
  '4-pack domestic beer - mix and match 4x341ml bottles. Choose from Coors Light and Molson Export. Take-out and delivery only.',
  'alcoholic-beverages',
  14.95),
 (1,
  'Jackson-Triggs Chardonnay',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/fbad83d6-4807-4fdc-a294-68751b99747c.png',
  'Jackson-Triggs Chardonnay, 750 mL Bottle. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  7.82),
 (1,
  'Jackson-Triggs Merlot',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/16337e61-4bce-405c-9ee0-f3ffa70708ca.png',
  'Jackson-Triggs Merlot, 750 mL Bottle. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  11.92),
 (1,
  'Kim Crawford Sauvignon Blanc',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/05d31ea5-968c-4308-a0b1-bdeee3572667.png',
  'Kim Crawford Sauvignon Blanc, 750 ml Bottle. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  18.82),
 (1,
  'Jacob''S Creek Moscato',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/93e1377d-5baa-4257-8b05-05311a5249bb.png',
  'Jacob Creek Moscato, 750ml Bottle. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  10.38),
 (1,
  'Domaine Laroche La Chevalière Chardonnay',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/bdc3cafd-1bf2-4680-be8f-19afbb4c241a.png',
  'White wine Domaine Laroche La Chevalière, Chardonnay, 750 ml. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  4.72),
 (1,
  'Domaine Laroche La Chevalière Pinot Noir',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/94025905-4fc3-46dc-b83d-6d99fe7628b6.png',
  'Red wine Domaine Laroche La Chevalière, Pinot noir, 750 ml. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  6.4),
 (1,
  'Folonari Pinot Grigio',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/a84ea9a8-fd6c-46d4-b6ff-ea2bde4c61fa.png',
  'White wine Folonari, Pinot grigio, 750 ml. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  8.85),
 (1,
  'Josh Cellars Cabernet Sauvignon',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/ae7ea97e-398e-47ec-88ad-1d66449ba1c1.png',
  'Josh Cellars Cabernet Sauvignon, 750 mL Bottle. Must be legal drinking age. Terms and Conditions apply. Take-out and Delivery only.',
  'alcoholic-beverages',
  13.27),
 (1,
  'Smirnoff Ice',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e4762cb6-6a78-47ad-8ee0-cc5e092a5e3c.png',
  'Smirnoff Ice, 355 mL Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  5.58),
 (1,
  'White Claw Mango',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/82e1bdf7-a561-4a3b-879e-12984aca2029.png',
  'White Claw Mango, 355ml Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  3.69),
 (1,
  'White Claw Black Cherry',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/8bc559e4-0c94-4b4b-b32d-3ee37fe8c507.png',
  'White Claw Black Cherry, 355ml Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  8.2),
 (1,
  'White Claw Natural Lime',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/afb0bd9e-710c-4754-a8cc-3762e6f0a59d.png',
  'White Claw Natural Lime, 355ml Can. Available in Singles and 6-packs. TAKE OUT / DELIVERY ONLY.',
  'alcoholic-beverages',
  20.74),
 (1,
  'Spirits - 200Ml Bottle',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/3fe2a304-9cca-472d-830a-f76e8d5d6bc1.png',
  'Choose one 200ml bottle of Absolut Vodka, J.P. Wiser’s Deluxe Whisky, Bacardi Superior White Rum or Captain Morgan Spiced Rum. Take-out and delivery only.',
  'alcoholic-beverages',
  8.9),
  (1,
  '12 Oz Can Of Pop',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/a871294a-76f5-4fa6-96ea-28b09091c8be.png',
  '7Up®, Pepsi®, Diet Pepsi®, MUG® Root Beer, Brisk® Iced Tea 12 Oz can. Delivery / Pick-Up only.',
  'beverages',
  5.32),
 (1,
  '6-Pack Of 12 Oz Cans Of Pop',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/bfa1d412-7c50-4168-8e46-15aba9d9f653.png',
  '7Up®, Pepsi®, Diet Pepsi®, MUG® Root Beer, Brisk® Iced Tea 12 Oz can. Delivery / Pick-Up only.',
  'beverages',
  6.31),
 (1,
  'Single Bottle Of Pop',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/9f7d6b47-dcc3-4977-b2c0-1fa5ab6d79c7.png',
  '7Up®, Pepsi®, Diet Pepsi®, MUG® Root Beer, Brisk® Iced Tea 591 mL Bottle. Delivery / Pick-Up only.',
  'beverages',
  5.53),
 (1,
  '4 Bottles Of Pop',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/9f7d6b47-dcc3-4977-b2c0-1fa5ab6d79c7.png',
  '7Up®, Pepsi®, Diet Pepsi®, MUG® Root Beer, Brisk® Iced Tea 591 mL Bottle. Delivery / Pick-Up only.',
  'beverages',
  2.73),
 (1,
  'Bottle Water',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/bc0471ae-e1ba-42b1-9ee2-e955b0d78fba.png',
  'Aquafina® Bottled Water (591ml)',
  'beverages',
  2.15),
 (1,
  'Fever Tree Ginger Beer',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/75d3ecf7-f6e1-44f3-a7a0-040d88e76219.png',
  '200mL Bottle',
  'beverages',
  3.78),
 (1,
  'Red Bull Energy Drink',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/e013d19e-bd82-43fe-9d77-26a655690ef9.png',
  'Red Bull Energy Drink contains high quality ingredients that vitalize body and mind®. 250mL.',
  'beverages',
  6.22),
 (1,
  'Red Bull Sugarfree',
  'https://bp-ca-cdn.tillster.com/menu-images/prod/77e22eb2-6d6e-45d6-80d4-a7aea9265dab.png',
  'Red Bull Sugarfree contains the same high quality ingredients as Red Bull Energy Drink – just without the sugar! Red Bull vitalizes body and mind®. 250mL.',
  'beverages',
  4.27);
